Algoritmo "ENQUANTO"
// Jean Carlos Nogueira
// Jean Carlos Nogueira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 1/31/2024
Var

   soma, i : inteiro


Inicio
      escreva("ditite um numero :")
      leia(soma)
      enquanto soma <> 99 faca
               escreval("Teste : ", aleatorio)
               soma <-soma +1
      fimenquanto

Fimalgoritmo