Algoritmo "multiplos"
// Jean Carlos Nogueira
// Jean Carlos Nogueira
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 1/30/2024
Var

   X, Y : INTEIRO
Inicio

   ESCREVAL("Digite dois numeros inteiros:" )
   LEIA(X)
   LEIA(Y)

   SE (X % Y = 0) OU (Y % X = 0) ENTAO
      ESCREVAL("Sao multiplos !")
   SENAO
      ESCREVAL("Nao sao multiplos")
   FIMSE



Fimalgoritmo
