Algoritmo "pares_consecutivos"
// Jean Carlos Nogueira
// Jean Carlos Nogueira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2/1/2024
Var

 x, soma : inteiro

Inicio

      escreva("Digite um numero inteiro: ")
      leia(x)
      
      se x % 2 <> 0 entao
         x <- x +1
      fimse

      soma <- (5 * x) +20
      
      escreval("SOMA =", soma)

Fimalgoritmo