Algoritmo "senha_fixa"
// Jean Carlos Nogueira
// Jean Carlos Nogueira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2/1/2024
Var

   senha : inteiro

Inicio

      escreva("Digite a senha: ")
      leia(senha)
      
      enquanto senha <> 2002 faca
               escreva("Senha Invalida! Tente novamente:")
               leia(senha)
      fimenquanto

      escreval("Acesso permitido!")


Fimalgoritmo