Algoritmo "sequencia_impares"
// Jean Carlos Nogueira
// Jean Carlos Nogueira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2/1/2024
Var

   x, s : inteiro

Inicio

      escreva("Digite o valor de X: ")
      leia(x)
      s <-0
      para s de 0 ate x faca
           se s % 2 <>0 entao
              escreval(s)
           fimse
      fimpara



Fimalgoritmo