Algoritmo "tabuada"
// Jean Carlos Nogueira
// Jean Carlos Nogueira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2/1/2024
Var

 x, y, s : inteiro


Inicio

      escreva("Deseja a tabuada para qual valor? ")
      leia(x)
      y <- 0
      para y de 0 ate 10 faca

           escreval(x," X ", y, " = ", s)
           y <- y + x
           s <- s + x
      fimpara


Fimalgoritmo